// Scope-checking middleware, applied via `axum::middleware::from_fn` on specific
// route groups. Each scope gets its own named thunk (e.g. `series_read`) so routes
// read as self-documenting annotations; all delegate to `check_scope`.
//
// `auth_interceptor` (auth.rs) determines IF a client is authenticated and WHAT
// scopes they have; `check_scope` enforces that a specific scope is present. When
// auth is disabled (no password) every request is given all scopes, so checks pass.

use crate::error::AppError;
use axum::{
    extract::Request,
    http::{StatusCode, header},
    middleware::Next,
    response::{IntoResponse, Response},
};
use jumbie_shared::auth::ApiScope;

/// 401 for a request with no injected scopes (auth did not run or failed). Carries
/// the `WWW-Authenticate` challenge a 401 is required to send.
fn unauthorized() -> Response {
    (
        StatusCode::UNAUTHORIZED,
        [(header::WWW_AUTHENTICATE, "Basic realm=\"jumbie\"")],
    )
        .into_response()
}

/// 403 for an authenticated caller whose key lacks `required`. Delegates to
/// [`AppError::insufficient_scope`], the SSoT for naming the required/missing
/// scopes and for the RFC 6750 `WWW-Authenticate` challenge.
fn insufficient_scope(required: &[ApiScope], granted: &[ApiScope]) -> Response {
    AppError::insufficient_scope(required, granted).into_response()
}

/// Generic scope checker. Reads the scope vector from `req.extensions()` (set by
/// auth_interceptor) and runs the request when any of the client's scopes
/// `permits(required_scope)`.
///
/// Returns 401 when no scope vector was injected, or a 403 describing the missing
/// scope otherwise.
pub async fn check_scope(required_scope: ApiScope, req: Request, next: Next) -> Response {
    // Decide from a borrowed read so the request can be moved into `next` on the
    // happy path without cloning the scope list.
    let allowed = req
        .extensions()
        .get::<Vec<ApiScope>>()
        .map(|scopes| scopes.iter().any(|s| s.permits(required_scope)));

    match allowed {
        None => unauthorized(),
        Some(true) => next.run(req).await,
        Some(false) => {
            let granted = req
                .extensions()
                .get::<Vec<ApiScope>>()
                .cloned()
                .unwrap_or_default();
            insufficient_scope(&[required_scope], &granted)
        }
    }
}

// Named wrapper functions generated by `make_scope_fn!` — one per ApiScope variant,
// named `{domain}_{action}` to match the enum (e.g. ApiScope::SeriesRead →
// scope::series_read).

macro_rules! make_scope_fn {
    ($name:ident, $scope:ident) => {
        pub async fn $name(req: Request, next: Next) -> Response {
            check_scope(ApiScope::$scope, req, next).await
        }
    };
}

make_scope_fn!(series_read, SeriesRead);
make_scope_fn!(series_write, SeriesWrite);
make_scope_fn!(config_read, ConfigRead);
make_scope_fn!(config_write, ConfigWrite);
make_scope_fn!(files_read, FilesRead);
make_scope_fn!(files_write, FilesWrite);
make_scope_fn!(queue_read, QueueRead);
make_scope_fn!(queue_write, QueueWrite);
make_scope_fn!(system_read, SystemRead);
make_scope_fn!(search, Search);
make_scope_fn!(auth_read, AuthRead);
make_scope_fn!(auth_write, AuthWrite);
make_scope_fn!(logs_read, LogsRead);
make_scope_fn!(plugins_read, PluginsRead);
make_scope_fn!(plugins_write, PluginsWrite);
make_scope_fn!(activity_read, ActivityRead);
make_scope_fn!(wanted_read, WantedRead);
make_scope_fn!(rename_read, RenameRead);
make_scope_fn!(rename_write, RenameWrite);

/// Compound scope: search + queue:write. Auto-season search triggers downloads,
/// which needs both; a single-scope check would not suffice. Checking both here
/// avoids a confusing 403 for whichever scope happened to be checked first.
pub async fn search_and_queue_write(req: Request, next: Next) -> Response {
    let Some(granted) = req.extensions().get::<Vec<ApiScope>>().cloned() else {
        return unauthorized();
    };

    let required = [ApiScope::Search, ApiScope::QueueWrite];
    if required
        .iter()
        .all(|need| granted.iter().any(|have| have.permits(*need)))
    {
        next.run(req).await
    } else {
        insufficient_scope(&required, &granted)
    }
}
